# Section 03: Matrices
### `01-What's a matrix?` 

In R, a matrix is a collection of elements of the same data type (numeric, character, or logical) arranged into a fixed number of rows and columns. Since you are only working with rows and columns, a matrix is called two-dimensional.

You can construct a matrix in R with the matrix() function. Consider the following example:

`matrix(1:9, byrow = TRUE, nrow = 3)`

In the matrix() function:

- The first argument is the collection of elements that R will arrange into the rows and columns of the matrix. Here, we use 1:9 which is a shortcut for c(1, 2, 3, 4, 5, 6, 7, 8, 9).
- The argument byrow indicates that the matrix is filled by the rows. If we want the matrix to be filled by the columns, we just place byrow = FALSE.
- The third argument nrow indicates that the matrix should have three rows.


`Coding:` 

- Construct a matrix with 3 rows containing the numbers 1 up to 9, filled row-wise.





In [24]:
matrix(1:9, byrow = TRUE, nrow = 3)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [25]:
matrix(1:9, byrow = FALSE, nrow = 3)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

### `02-Analyze matrices, you shall`
- Use `c(new_hope, empire_strikes, return_jedi)` to combine the three vectors into one vector. Call this vector `box_office`.
- Construct a matrix with 3 rows, where each row represents a movie. Use the `matrix()` function to do this. The first argument is the vector `box_office`, containing all box office figures. Next, you'll have to specify `nrow = 3` and `byrow = TRUE`. Name the resulting matrix `star_wars_matrix`.

In [26]:
# Box office Star Wars (in millions!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Create box_office
box_office <- c(new_hope, empire_strikes, return_jedi)

# Construct star_wars_matrix
star_wars_matrix <- matrix(box_office, byrow=TRUE, nrow = 3)
star_wars_matrix

[,1]    [,2] 
[1,] 460.998 314.4
[2,] 290.475 247.9
[3,] 309.306 165.8

### `03-Naming a matrix`
* Use `colnames()` to name the columns of `star_wars_matrix` with the `region` vector.
* Use `rownames()` to name the rows of `star_wars_matrix` with the `titles` vector.
* Print out `star_wars_matrix` to see the result of your work.


In [27]:
# Box office Star Wars (in millions!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Construct matrix
star_wars_matrix <- matrix(c(new_hope, empire_strikes, return_jedi), nrow = 3, byrow = TRUE)

# Vectors region and titles, used for naming
region <- c("US", "non-US")
titles <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")

# Name the columns with region
colnames(star_wars_matrix) <- region 

# Name the rows with titles
rownames(star_wars_matrix) <- titles

# Print out star_wars_matrix
star_wars_matrix

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

### `04-Calculating the worldwide box office`
- Calculate the worldwide box office figures for the three movies and put these in the vector named worldwide_vector.

In [28]:
# Construct star_wars_matrix
box_office <- c(460.998, 314.4, 290.475, 247.900, 309.306, 165.8)
region <- c("US", "non-US")
titles <- c("A New Hope", 
                 "The Empire Strikes Back", 
                 "Return of the Jedi")
               
star_wars_matrix <- matrix(box_office, 
                      nrow = 3, byrow = TRUE,
                      dimnames = list(titles, region))

# Calculate worldwide box office figures
worldwide_vector <- rowSums(star_wars_matrix)
worldwide_vector

A New Hope The Empire Strikes Back      Return of the Jedi 
                775.398                 538.375                 475.106

### `05-Adding a column for the Worldwide box office`
In the previous exercise you calculated the vector that contained the worldwide box office receipt for each of the three Star Wars movies. However, this vector is not yet part of star_wars_matrix.

You can add a column or multiple columns to a matrix with the cbind() function, which merges matrices and/or vectors together by column. For example:

`big_matrix <- cbind(matrix1, matrix2, vector1 ...)` 


* Add `worldwide_vector` as a new column to the `star_wars_matrix` and assign the result to `all_wars_matrix`. Use the `cbind()` function.




In [29]:
# Construct star_wars_matrix
box_office <- c(460.998, 314.4, 290.475, 247.900, 309.306, 165.8)
region <- c("US", "non-US")
titles <- c("A New Hope", 
            "The Empire Strikes Back", 
            "Return of the Jedi")
               
star_wars_matrix <- matrix(box_office, 
                      nrow = 3, byrow = TRUE,
                      dimnames = list(titles, region))

# The worldwide box office figures
worldwide_vector <- rowSums(star_wars_matrix)

# Bind the new variable worldwide_vector as a column to star_wars_matrix
all_wars_matrix <- cbind(star_wars_matrix, worldwide_vector)
all_wars_matrix

US      non-US worldwide_vector
A New Hope              460.998 314.4  775.398         
The Empire Strikes Back 290.475 247.9  538.375         
Return of the Jedi      309.306 165.8  475.106

### `06-Adding a row`
* Use `rbind()` to paste together `star_wars_matrix` and `star_wars_matrix2`, in this order. Assign the resulting matrix to `all_wars_matrix`.

In [30]:
box_office1 <- c(461.0, 314.4, 290.5, 247.9, 309.3, 165.8)
box_office2 <- c(474.5, 552.5, 310.7, 338.7, 380.3, 468.5)
region <- c("US", "non-US")
titles <- c("A New Hope",
            "The Empire Strikes Back",
            "Return of the Jedi")

# star_wars_matrix and star_wars_matrix2 are available in your workspace
star_wars_matrix <- matrix(box_office1, nrow=3, byrow=TRUE, dimnames = list(titles, region))
star_wars_matrix2 <- matrix(box_office2, nrow=3, byrow=TRUE, dimnames = list(titles, region))

star_wars_matrix
star_wars_matrix2

US    non-US
A New Hope              461.0 314.4 
The Empire Strikes Back 290.5 247.9 
Return of the Jedi      309.3 165.8

US    non-US
A New Hope              474.5 552.5 
The Empire Strikes Back 310.7 338.7 
Return of the Jedi      380.3 468.5

In [31]:
# Combine both Star Wars trilogies in one matrix
all_wars_matrix <- rbind(star_wars_matrix, star_wars_matrix2)
all_wars_matrix

US    non-US
A New Hope              461.0 314.4 
The Empire Strikes Back 290.5 247.9 
Return of the Jedi      309.3 165.8 
A New Hope              474.5 552.5 
The Empire Strikes Back 310.7 338.7 
Return of the Jedi      380.3 468.5

### `7-The total box office revenue for the entire saga`

Just like `cbind()` has `rbind()`, `colSums()` has `rowSums()`. Your R workspace already contains the `all_wars_matrix` that you constructed in the previous exercise; type `all_wars_matrix` to have another look. Let's now calculate the total box office revenue for the entire saga.

* Calculate the total revenue for the US and the non-US region and assign `total_revenue_vector`. You can use the `colSums()` function.
* Print out `total_revenue_vector` to have a look at the results.



In [32]:
# all_wars_matrix is available in your workspace
all_wars_matrix

# Total revenue for US and non-US
total_revenue_vector <- colSums(all_wars_matrix)
  
# Print out total_revenue_vector
total_revenue_vector

US    non-US
A New Hope              461.0 314.4 
The Empire Strikes Back 290.5 247.9 
Return of the Jedi      309.3 165.8 
A New Hope              474.5 552.5 
The Empire Strikes Back 310.7 338.7 
Return of the Jedi      380.3 468.5

US non-US 
2226.3 2087.8

### `8-Selection of matrix elements`

- Select the non-US revenue for all movies (the entire second column of `all_wars_matrix`), store the result as `non_us_all`.
- Use `mean()` on `non_us_all` to calculate the average non-US revenue for all movies. Simply print out the result.
- This time, select the non-US revenue for the first two movies in `all_wars_matrix`. Store the result as `non_us_some`.
- Use `mean()` again to print out the average of the values in `non_us_some`.

In [33]:
# all_wars_matrix is available in your workspace
all_wars_matrix[]

# Select the non-US revenue for all movies
non_us_all <- all_wars_matrix[,2]
  
# Average non-US revenue
mean(non_us_all)
  
# Select the non-US revenue for first two movies
non_us_some <- all_wars_matrix[1:2,2]
  
# Average non-US revenue for first two movies
mean(non_us_some)

US    non-US
A New Hope              461.0 314.4 
The Empire Strikes Back 290.5 247.9 
Return of the Jedi      309.3 165.8 
A New Hope              474.5 552.5 
The Empire Strikes Back 310.7 338.7 
Return of the Jedi      380.3 468.5

[1] 347.9667

[1] 281.15

### `09-A little arithmetic with matrices`
* Divide `all_wars_matrix` by 5, giving you the number of visitors in millions. Assign the resulting matrix to `visitors`.
* Print out `visitors` so you can have a look.

In [34]:
# all_wars_matrix is available in your workspace
all_wars_matrix

# Estimate the visitors
visitors <- all_wars_matrix / 5 
  
# Print the estimate to the console
visitors

US    non-US
A New Hope              461.0 314.4 
The Empire Strikes Back 290.5 247.9 
Return of the Jedi      309.3 165.8 
A New Hope              474.5 552.5 
The Empire Strikes Back 310.7 338.7 
Return of the Jedi      380.3 468.5

US    non-US
A New Hope              92.20  62.88
The Empire Strikes Back 58.10  49.58
Return of the Jedi      61.86  33.16
A New Hope              94.90 110.50
The Empire Strikes Back 62.14  67.74
Return of the Jedi      76.06  93.70

### `10-A little arithmetic with matrices (2)`
* Divide `all_wars_matrix` by `ticket_prices_matrix` to get the estimated number of US and non-US visitors for the six movies. Assign the result to `visitors`.
* From the `visitors` matrix, select the entire first column, representing the number of visitors in the US. Store this selection as `us_visitors`.
* Calculate the average number of US visitors; print out the result.

In [40]:
price <- c(5.0, 6.0, 7.0, 4.0, 4.5, 4.9, 5.0, 6.0, 7.0, 4.0, 4.5, 4.9)
region <- c("US","non-US")
titles <- c("A New Hope",
            "The Empire Strikes Back",
            "Return of the Jedi",
            "A New Hope",
            "The Empire Strikes Back",
            "Return of the Jedi")

ticket_prices_matrix <- matrix(price, nrow=6, byrow=TRUE, dimnames = list(titles, region))

In [43]:
# all_wars_matrix and ticket_prices_matrix are available in your workspace
all_wars_matrix
ticket_prices_matrix

# Estimated number of visitors
visitors <- all_wars_matrix / ticket_prices_matrix

# US visitors
us_visitors <- visitors[,1]

# Average number of US visitors
mean(us_visitors)

US    non-US
A New Hope              461.0 314.4 
The Empire Strikes Back 290.5 247.9 
Return of the Jedi      309.3 165.8 
A New Hope              474.5 552.5 
The Empire Strikes Back 310.7 338.7 
Return of the Jedi      380.3 468.5

US  non-US
A New Hope              5.0 6.0   
The Empire Strikes Back 7.0 4.0   
Return of the Jedi      4.5 4.9   
A New Hope              5.0 6.0   
The Empire Strikes Back 7.0 4.0   
Return of the Jedi      4.5 4.9

[1] 71.03836

### `The End` 