# Section 01: Conditionals and Control Flow




### `01-Equality`
- In the editor on the right, write R code to see if `TRUE` equals `FALSE`.
- Likewise, check if `-6 * 14` is not equal to `17 - 101`.
- Next up: comparison of character strings. Ask R whether the strings "useR" and "user" are equal.
- Finally, find out what happens if you compare logicals to numerics: are `TRUE` and 1 equal?

In [1]:
# Comparison of logicals
TRUE == FALSE

# Comparison of numerics
-6 * 14 != 17 - 101 

# Comparison of character strings
"useR" == "user"

# Compare a logical with a numeric
TRUE == 1 

[1] FALSE

[1] FALSE

[1] FALSE

[1] TRUE

### `02 Greater and less than`
Write R expressions to check whether:
- `-6 * 5 + 2` is greater than or equal to `-10 + 1`.
- "raining" is less than or equal to "raining dogs".
- TRUE is greater than FALSE.

In [2]:
# Comparison of numerics
-6 * 5 + 2 >= -10 + 1

# Comparison of character strings
"raining" <= "raining dogs" 

# Comparison of logicals
TRUE > FALSE

[1] FALSE

[1] TRUE

[1] TRUE

### `03-Compare vectors`
Using relational operators, find a logical answer, i.e. `TRUE` or `FALSE`, for the following questions:

- On which days did the number of LinkedIn profile views exceed 15?
- When was your LinkedIn profile viewed only 5 times or fewer?
- When was your LinkedIn profile visited more often than your Facebook profile?

In [3]:
# The linkedin and facebook vectors have already been created for you
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
facebook <- c(17, 7, 5, 16, 8, 13, 14)

# Popular days
linkedin > 15 

# Quiet days
linkedin <= 5 

# LinkedIn more popular than Facebook
linkedin > facebook

[1]  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE

[1] FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE

### `04-Compare matrices`
Using the relational operators you've learned so far, try to discover the following:

- When were the views exactly equal to 13? Use the `views` matrix to return a logical matrix.
- For which days were the number of views less than or equal to 14? Again, have R return a logical matrix.

In [4]:
# The social data has been created for you
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
facebook <- c(17, 7, 5, 16, 8, 13, 14)
views <- matrix(c(linkedin, facebook), nrow = 2, byrow = TRUE)

# When does views equal 13?
views == 13

# When is views less than or equal to 14?
views <= 14

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7] 
[1,] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE

[,1]  [,2] [,3] [,4]  [,5] [,6]  [,7]
[1,] FALSE TRUE TRUE  TRUE TRUE FALSE TRUE
[2,] FALSE TRUE TRUE FALSE TRUE  TRUE TRUE

### `05-& and |`

Write R expressions to solve the following questions concerning the variable last:

- Is `last` under 5 or above 10?
- Is `last` between 15 and 20, excluding 15 but including 20?

In [5]:
# The linkedin and last variable are already defined for you
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
last <- tail(linkedin, 1)

# Is last under 5 or above 10?
last < 5 | last > 10 

# Is last between 15 (exclusive) and 20 (inclusive)?
last > 15 & last <= 20

[1] TRUE

[1] FALSE

### `06-& and | (2)`

- When did LinkedIn views exceed 10 and did Facebook views fail to reach 10 for a particular day? Use the `linkedin` and `facebook` vectors.
- When were one or both of your LinkedIn and Facebook profiles visited at least 12 times?
- When is the `views` matrix equal to a number between 11 and 14, excluding 11 and including 14?

In [7]:
linkedin
facebook
views

[1] 16  9 13  5  2 17 14

[1] 17  7  5 16  8 13 14

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 16   9    13    5   2    17   14  
[2,] 17   7     5   16   8    13   14

In [8]:
# The social data (linkedin, facebook, views) has been created for you

# linkedin exceeds 10 but facebook below 10
linkedin > 10 & facebook < 10

# When were one or both visited at least 12 times?
linkedin >= 12 | facebook >= 12

# When is views between 11 (exclusive) and 14 (inclusive)?
views > 11 & views <= 14

[1] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE

[1]  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]
[1,] FALSE FALSE  TRUE FALSE FALSE FALSE TRUE
[2,] FALSE FALSE FALSE FALSE FALSE  TRUE TRUE

### `07-Reverse the result: !`
- What would the following set of R expressions return?



In [9]:
x <- 5
y <- 7
!(!(x < 4) & !!!(y > 12))

[1] FALSE

### `08-Blend it all together`
- Select the entire second column, named `day2`, from the `li_df` data frame as a vector and assign it to `second`.
- Use `second` to create a logical vector, that contains `TRUE` if the corresponding number of views is strictly greater than 25 or strictly lower than 5 and FALSE otherwise. Store this logical vector as extremes.
- Use sum() on the extremes vector to calculate the number of TRUEs in extremes (i.e. to calculate the number of employees that are either very popular or very low-profile). Simply print this number to the console.


In [15]:
li_df <- read.csv("C:\\Users\\mosman\\Desktop\\Github\\Data_Scientist_with_R\\00_Datasets\\li_df.csv",
                   header=TRUE)

In [18]:
# li_df is pre-loaded in your workspace

# Select the second column, named day2, from li_df: second
second <- c(li_df[,"day2"])

# Build a logical vector, TRUE if value in second is extreme: extremes
extremes <- c(second > 25 | second < 5)

# Count the number of TRUEs in extremes
sum(extremes)

[1] 16

### `The End` 